[package]
name = "Voxel_Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
gpu-allocator = "0.27.0"
vk-sync = "0.1.6"
winit = "0.30.9"
raw-window-handle = "0.6.0"  # Needed for winit + Vulkan integration
